apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: canary-rollout
    repoURL: https://github.com/alina-codefresh/rollouts-demo.git
    targetRevision: 1.23k8s
  destination:
    name: alina-1
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
